AWSTemplateFormatVersion: '2010-09-09'
Resources:
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: arn:aws:iam::<account-id>:role/CodePipelineServiceRole
      ArtifactStore:
        Type: S3
        Location: <artifact-bucket>
      Stages:
        - Name: Source
          Actions:
            - Name: GitHub_Source
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              Configuration:
                Owner: <github-user>
                Repo: <github-repo>
                Branch: main
                OAuthToken: <token>
              OutputArtifacts:
                - Name: SourceOutput
        - Name: Build
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName: service-a-build
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput
        - Name: Deploy
          Actions:
            - Name: DeployToEKS
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: EKS
                Version: 1
              Configuration:
                ClusterName: dev-cluster
                KubernetesNamespace: default
                ActionMode: APPLY
                RoleArn: arn:aws:iam::<account-id>:role/EKSDeployRole
                ManifestFile: service-a/manifests/deployment.yaml
              InputArtifacts:
                - Name: BuildOutput
