version: 0.2
env:
  variables:
    SERVICE_NAME: service-a
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password | docker login --username AWS --password-stdin 253603915156.dkr.ecr.ap-south-1.amazonaws.com/service-a
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - pwd
      - ls -a
      - pwd
      - cd service-a
      - mvn clean package -DskipTests
      - docker build -t $SERVICE_NAME:$IMAGE_TAG .
      - docker tag $SERVICE_NAME:$IMAGE_TAG 253603915156.dkr.ecr.ap-south-1.amazonaws.com/$SERVICE_NAME:$IMAGE_TAG
  post_build:
    commands:
      - docker push 253603915156.dkr.ecr.ap-south-1.amazonaws.com/$SERVICE_NAME:$IMAGE_TAG
      - echo Writing image definitions...
      - printf '[{"name":"%s","imageUri":"%s"}]' "$SERVICE_NAME" "253603915156.dkr.ecr.ap-south-1.amazonaws.com/$SERVICE_NAME:$IMAGE_TAG" > imagedefinitions.json
      - cd ..
      - cat imagedefinitions.json
artifacts:
  files: 
    - imagedefinitions.json
    - app.jar
